data:
  corpus_1:
    path_src: dataset/TPL/client_9/src-train.txt
    path_tgt: dataset/TPL/client_9/tgt-train.txt
  valid:
    path_src: dataset/vocab/empty.txt
    path_tgt: dataset/vocab/empty.txt

n_sample: 0
save_data: ./dataset/vocab/example
src_vocab: ./dataset/vocab/example.vocab.src
tgt_vocab: ./dataset/vocab/example.vocab.src
share_vocab: 'true'
src_seq_length: 500
tgt_seq_length: 500
overwrite: 'true'

# train_from: ./exp/official_pretrained/product_pretrained.pt
reset_optim: 'all'
save_model: exp/tmp/p2r
save_checkpoint_steps: 10000
keep_checkpoint: 40
seed: 3435
train_steps: 10000
valid_steps: 100000
warmup_steps: 8000
report_every: 100000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: none
learning_rate: 0.0002
max_grad_norm: 0.0

batch_size: 64
valid_batch_size: 64
batch_type: sents
normalization: sents
dropout: 0.1
attention_dropout: 0.3
label_smoothing: 0.0

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0
